### ISSUE TITLE
medspacy.load(enable)  seems to ignore "medspacy_quickumls" in the component list

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#167] opened 2022-10-28 13:47 UTC
Please check notebook notebook 11a.  Cell 4 attempts to enable a list of components including "medspacy_quickumls".  Cell 5 displays the components actually loaded.  "medspacy_quickumls" is not among them.    If one does a manual medspacy.add_pipe("medspacy_quickumls") afterward, it loads fine, so I think there is a flaw in the enable logic.

**Comment by burgersmoke** [comment] 2022-11-03 16:53
@RonWilkinson Are you running this notebook on Windows?  If so, QuickUMLS (and therefore medspacy_quickumls) are not installed by default.  Did you run through these steps to install QuickUMLS manually following the medspacy install?

https://github.com/medspacy/medspacy/blob/master/windows_and_quickumls.md

**Comment by RonWilkinson** [comment] 2022-11-03 17:57
I’m running on Linux.  In any case, in my note I point out that I a manual add_pipe works when Load(activate) does not.  Add_pipe would not work if medspacy_quickumls were not installed.

--Ron

**Comment by burgersmoke** [comment] 2022-11-03 18:21
You are right.  Thank you for re-iterating that behavior.  We will look into this.

**Comment by burgersmoke** [comment] 2023-05-05 21:14
We are about to release a new medspacy version (1.1).  After that is released and stable, either @turbosheep  or myself can fix this so that "medspacy_quickumls" will be uncommented from this block in `util.py`:

```
ALL_PIPE_NAMES = {
    "medspacy_tokenizer",
    "medspacy_preprocessor",
    "medspacy_pyrush",
    "medspacy_target_matcher",
    # "medspacy_quickumls", # quickumls still not included by default due to install issues
    "medspacy_context",
    "medspacy_sectionizer",
    "medspacy_postprocessor",
    "medspacy_doc_consumer",
}
```

**Comment by burgersmoke** [comment] 2023-05-05 21:14
In other words, we will fix this, but I think we want to make sure we have at least a stable week of new usage before we flip the switch.

**Comment by burgersmoke** [comment] 2023-05-26 19:47
@turbosheep This should be possible to fix now with 1.1.2.  Could you add a test for this to make sure it works with `medspacy.load()`.

**Comment by ivcvy** [comment] 2023-10-15 00:13
hi @burgersmoke I'm encountering the same issue. I'm running on linux and have medspacy 1.1.2, medspacy-quickumls 3.0 installed. I tried uncommenting medspacy_quickumls in ALL_PIPE_NAMES within util.py.

**Comment by ivcvy** [comment] 2023-10-17 08:51
concurrent medspacy and quickumls installation results in this error message when adding pipe:
ValueError: [E002] Can't find factory for 'medspacy_quickumls' for language English (en).
managed to initialize UMLS resources by running this without installing quickumls:
python -m quickumls.install <umls_installation_path> <destination_path>

**Comment by burgersmoke** [comment] 2023-10-17 15:04
@ivcvy  Are you unblocked at the moment then?  Sorry we don't have a lot of additional time to address issues since medspacy is something we support on the side of other work priorities.

I did want to make sure that you are running again since I would not have expected that the error you report:

`Can't find factory for 'medspacy_quickumls' for language English`

to have been solved by generating UMLS resources.  The error above to me looks like python module for quickumls not being imported before any calls to 
`nlp.add_pipe("medspacy_quickumls")` 
(whether as a part of `madspacy.load()` or a manual call)

**Comment by ivcvy** [comment] 2023-10-18 01:16
@burgersmoke Thank you for your support.
My intention was to use full UMLS resource using medspacy_quickumls and it works at the moment. I did not intend to install quickumls and use it as standalone, but I thought I have to install quickumls before generating UMLS resource (following the [guide](https://github.com/Georgetown-IR-Lab/QuickUMLS)). Just posting here in case anybody will find it helpful.
The error is reproducible when running notebook 11b in venv with medspacy and quickumls installed.

**Comment by jianlins** [comment] 2024-11-21 22:34
This should have been resolved in our latest release

**Closed by jianlins** 2024-11-21 22:34 UTC
